## 판다스 동계 함수

In [6]:
pip install python=3.10

Note: you may need to restart the kernel to use updated packages.

ERROR: Invalid requirement: 'python=3.10': Expected semicolon (after name with no version specifier) or end
    python=3.10
          ^
Hint: = is not a valid operator. Did you mean == ?

### 기본 통계 함수

In [1]:
import pandas as pd
titanic_data = 'https://raw.githubusercontent.com/sehakflower/data/main/titanic.csv'
titanic_df = pd.read_csv(titanic_data, sep="\t")
titanic_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  156 non-null    int64
 1   Survived     156 non-null    int64
 2   Pclass       156 non-null    int64
 3   Name         156 non-null    str
 4   Sex          156 non-null    str
 5   Age          126 non-null    float64
 6   SibSp        156 non-null    int64
 7   Parch        156 non-null    int64
 8   Ticket       156 non-null    str
 9   Fare         156 non-null    float64
 10  Cabin        31 non-null     str
 11  Embarked     155 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 14.8 KB

In [3]:
# 컬럼 소문자
new_columns = []
for col in titanic_df.columns:
    # new_columns.append(col.lower())
    new_columns.append(col[0].lower() + col[1:])
titanic_df.columns = new_columns

In [4]:
# 데이터의 통계치 확인하기
titanic_df.describe()

,passengerId,survived,pclass,age,sibSp,parch,fare
count,156.000000,156.000000,156.000000,126.000000,156.000000,156.000000,156.000000
mean,78.500000,0.346154,2.423077,28.141508,0.615385,0.397436,28.109587
std,45.177428,0.477275,0.795459,14.613880,1.056235,0.870146,39.401047
min,1.000000,0.000000,1.000000,0.830000,0.000000,0.000000,6.750000
25%,39.750000,0.000000,2.000000,19.000000,0.000000,0.000000,8.003150
50%,78.500000,0.000000,3.000000,26.000000,0.000000,0.000000,14.454200
75%,117.250000,1.000000,3.000000,35.000000,1.000000,0.000000,30.371850
max,156.000000,1.000000,3.000000,71.000000,5.000000,5.000000,263.000000

In [5]:
# 합계 구하기 : sum 함수
titanic_df.sum()

passengerId                                                12246
survived                                                      54
pclass                                                       378
name           Braund, Mr. Owen HarrisCumings, Mrs. John Brad...
sex            malefemalefemalefemalemalemalemalemalefemalefe...
age                                                      3545.83
sibSp                                                         96
parch                                                         62
ticket         A/5 21171PC 17599STON/O2. 31012821138033734503...
fare                                                   4385.0956
cabin          C85C123E46G6C103D56A6C23 C25 C27B78D33B30C52B2...
embarked       SCSSSQSSSCSSSSSSQSSCSSQSSSCSQSCCQSCSCSSCSSCCQS...
dtype: object

In [7]:
# 총 개수 구하기 : count 함수
titanic_df.count()

passengerId    156
survived       156
pclass         156
name           156
sex            156
age            126
sibSp          156
parch          156
ticket         156
fare           156
cabin           31
embarked       155
dtype: int64

In [8]:
# 최댓값 구하기 : max 함수
titanic_df.max()

passengerId                                156
survived                                     1
pclass                                       3
name           van Billiard, Mr. Austin Blyler
sex                                       male
age                                       71.0
sibSp                                        5
parch                                        5
ticket                             W.E.P. 5734
fare                                     263.0
cabin                                       G6
embarked                                     S
dtype: object

In [9]:
# 최솟값 구하기 : min 함수
titanic_df.min()

passengerId                                                 1
survived                                                    0
pclass                                                      1
name           Ahlin, Mrs. Johan (Johanna Persdotter Larsson)
sex                                                    female
age                                                      0.83
sibSp                                                       0
parch                                                       0
ticket                                                 110465
fare                                                     6.75
cabin                                                      A5
embarked                                                    C
dtype: object

In [ ]:
# 평균값 구하기 : mean 함수, 버전 3.10은 (numeric_only=True) 없이
titanic_df.mean(numeric_only=True)

passengerId    78.500000
survived        0.346154
pclass          2.423077
age            28.141508
sibSp           0.615385
parch           0.397436
fare           28.109587
dtype: float64

In [15]:
# 중간값 구하기 : median 함수
titanic_df.median(numeric_only=True)

passengerId    78.5000
survived        0.0000
pclass          3.0000
age            26.0000
sibSp           0.0000
parch           0.0000
fare           14.4542
dtype: float64

In [ ]:
# 최빈값 구하기 : mad = mode 함수
titanic_df.mode(numeric_only=True)

     passengerId  survived  pclass   age  sibSp  parch  fare
0              1       0.0     3.0  21.0    0.0    0.0  8.05
1              2       NaN     NaN   NaN    NaN    NaN   NaN
2              3       NaN     NaN   NaN    NaN    NaN   NaN
3              4       NaN     NaN   NaN    NaN    NaN   NaN
4              5       NaN     NaN   NaN    NaN    NaN   NaN
..           ...       ...     ...   ...    ...    ...   ...
151          152       NaN     NaN   NaN    NaN    NaN   NaN
152          153       NaN     NaN   NaN    NaN    NaN   NaN
153          154       NaN     NaN   NaN    NaN    NaN   NaN
154          155       NaN     NaN   NaN    NaN    NaN   NaN
155          156       NaN     NaN   NaN    NaN    NaN   NaN

[156 rows x 7 columns]

In [21]:
# 분산 구하기 : var 함수
titanic_df.var(numeric_only=True)

passengerId    2041.000000
survived          0.227792
pclass            0.632754
age             213.565487
sibSp             1.115633
parch             0.757155
fare           1552.442481
dtype: float64